title: Tropical Fruit
author: rcarr421
email: rcarr421@evit.com
description: > 
 This site talks about all my hobbies and interest! I hope you look forward to seeing me upload pictures and videos about my life. I will try to keep you all posted as much as I can!

twitter_username: Mr_Cee09 
github_username:  rcarr421
show_excerpts: false 

theme: minima
---
title: "My first blog post title"
date: 2021-04-01
---
