title: Tropical Fruit
author: rcarr421
email: rcarr421@evit.com
description: > 
 This site talks about all my hobbies and interest!

twitter_username: Mr_Cee09 
github_username:  rcarr421
show_excerpts: false 

theme: minima
---
title: "My first blog post title"
date: 2021-04-01
---
