title: Tropical Fruit
author: rcarr421
email: rcarr421@evit.com
description: > # this means to ignore newlines until "baseurl:"
 This site talks about all my hobbies and interest!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  rcarr421 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
